version: 0.2

env:
  variables:
    SHELL: "/bin/bash"
phases:
  build:
    commands:
       - pip install -r requirements.txt -t .
       - python encrypt-template.py > cfn-encrypt.json
       - python datadog-template.py > cfn-datadog.json

artifacts:
  files:
    - '**/*'

