version: 0.2

env:
  variables:
    SHELL: "/bin/bash"
phases:
  build:
    commands:
       - cd tropo
       - pip install -r ../requirements.txt -t .
       - python dummy.py > ../dummy.json

artifacts:
  files:
    - 'dummy.json'
    - 'config-uat.json'
    - 'config-prod.json'
